import { mkdir, readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { parseTrackedTickers } from "../src/sec/config.ts";
const staging = process.argv.includes("--staging");
const source = JSON.parse(await readFile("workers/pipeline/wrangler.jsonc", "utf8"));
const config = { ...source, ...(staging ? source.env.staging : {}) };
delete config.env;
const id = process.env[staging ? "SEC_PIPELINE_STAGING_D1_DATABASE_ID" : "SEC_PIPELINE_D1_DATABASE_ID"]?.trim();
if (!id || id === "00000000-0000-4000-8000-000000000000" || !/^[0-9a-f]{8}-[0-9a-f-]{27}$/i.test(id)) throw new Error("Set the Pipeline D1 database id before deployment; production should use the existing analysis database.");
config.main = resolve("workers/pipeline/src/index.ts");
config.$schema = resolve("node_modules/wrangler/config-schema.json");
config.d1_databases = config.d1_databases.map((db: Record<string, string>) => ({ ...db, database_id: id, migrations_dir: resolve("workers/pipeline/migrations") }));
// Collection policy is injected deliberately; never silently deploy an empty production watchlist.
const tracked = process.env.SEC_TRACKED_TICKERS?.trim();
if (!tracked) throw new Error("Set SEC_TRACKED_TICKERS for the Pipeline deployment");
config.vars = { ...config.vars, SEC_TRACKED_TICKERS: parseTrackedTickers(tracked).join(",") };
await mkdir(".wrangler/deploy", { recursive: true });
const output = `.wrangler/deploy/pipeline${staging ? "-staging" : ""}.json`;
await writeFile(output, JSON.stringify(config, null, 2) + "\n");
console.log(`Prepared ${config.name}: ${output}`);
