/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/pipeline/wrangler.jsonc --include-runtime=false workers/pipeline/worker-configuration.d.ts` (hash: 05a345245f07fb94e604c571b3ccab02)
interface __BaseEnv_Env {
	SEC_FILINGS: R2Bucket;
	WEB_APP_ORIGIN: "https://earning-report-analysis-sec-web-staging.max-zhangyuchen.workers.dev" | "https://earning-report-analysis-sec-web.max-zhangyuchen.workers.dev";
	SEC_USER_AGENT: "earning-report-analysis/1.0 max.zhangyuchen@gmail.com";
	SEC_ANALYSIS_MODEL: "glm-5.3-flash";
	SEC_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./index").SecAnalysisWorkflow['run']>[0]['payload']>;
	SEC_MEMORY_WORKFLOW: Workflow<Parameters<import("./index").SecMemoryWorkflow['run']>[0]['payload']>;
	COMPANY_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./index").CompanyAnalysisWorkflow['run']>[0]['payload']>;
	COMPANY_ANALYSIS_BACKFILL_WORKFLOW: Workflow<Parameters<import("./index").CompanyAnalysisBackfillWorkflow['run']>[0]['payload']>;
	WEB?: Fetcher /* earning-report-analysis-sec-web */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface StagingEnv {
		SEC_FILINGS: R2Bucket;
		WEB_APP_ORIGIN: "https://earning-report-analysis-sec-web-staging.max-zhangyuchen.workers.dev";
		SEC_USER_AGENT: "earning-report-analysis/1.0 max.zhangyuchen@gmail.com";
		SEC_ANALYSIS_MODEL: "glm-5.3-flash";
		SEC_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./index").SecAnalysisWorkflow['run']>[0]['payload']>;
		SEC_MEMORY_WORKFLOW: Workflow<Parameters<import("./index").SecMemoryWorkflow['run']>[0]['payload']>;
		COMPANY_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./index").CompanyAnalysisWorkflow['run']>[0]['payload']>;
		COMPANY_ANALYSIS_BACKFILL_WORKFLOW: Workflow<Parameters<import("./index").CompanyAnalysisBackfillWorkflow['run']>[0]['payload']>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "WEB_APP_ORIGIN" | "SEC_USER_AGENT" | "SEC_ANALYSIS_MODEL">> {}
}
