/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/pipeline/wrangler.jsonc --include-runtime=false workers/pipeline/worker-configuration.d.ts` (hash: 05d43ec58f0511b1765ac80af0feccfc)
interface __BaseEnv_Env {
	SEC_FILINGS: R2Bucket;
	DB: D1Database;
	SEC_USER_AGENT: "earning-report-analysis/1.0 max.zhangyuchen@gmail.com";
	SEC_ANALYSIS_MODEL: "glm-5.3-flash";
	SEC_TRACKED_TICKERS: "";
	SEC_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./src/index").SecAnalysisWorkflow['run']>[0]['payload']>;
	SEC_MEMORY_WORKFLOW: Workflow<Parameters<import("./src/index").SecMemoryWorkflow['run']>[0]['payload']>;
	COMPANY_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./src/index").CompanyAnalysisWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		SEC_FILINGS: R2Bucket;
		DB: D1Database;
		SEC_USER_AGENT: "earning-report-analysis/1.0 max.zhangyuchen@gmail.com";
		SEC_ANALYSIS_MODEL: "glm-5.3-flash";
		SEC_TRACKED_TICKERS: "";
		SEC_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./src/index").SecAnalysisWorkflow['run']>[0]['payload']>;
		SEC_MEMORY_WORKFLOW: Workflow<Parameters<import("./src/index").SecMemoryWorkflow['run']>[0]['payload']>;
		COMPANY_ANALYSIS_WORKFLOW: Workflow<Parameters<import("./src/index").CompanyAnalysisWorkflow['run']>[0]['payload']>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SEC_USER_AGENT" | "SEC_ANALYSIS_MODEL" | "SEC_TRACKED_TICKERS">> {}
}
